POST http://127.0.0.1:5050/diary
Content-Type: application/json
Cookie: other=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZGF0YSI6eyJwYXNzd29yZCI6IiQyYiQxMCRQbGxuNU9ubEk4Ujd4QzFCTjFwdW1PYllvRVo3cE9EU3htdTY3djV2U2dvYmI3ZEhlak1QdSIsImxldmVsIjoxLCJzZWMiOjMyMjEsImRhdGEiOnsibmFtZSI6Ikh1YmVydCBGLiBFc3Bpbm9sYSBJIiwiZ2VuZGVyIjoiTWFsZSIsImFnZSI6MjIsImRpYXJ5Ijp7IkF1Zy4gMjIsIDIwMjIiOlsiRGF0ZSIsIkNvbnRlbnQiXSwidW5kZWZpbmVkIjpbIk90dyBIb21lIixudWxsXX19fSwiaWF0IjoxNjYxMjEzNDk1fQ.nx9Ih9MK-hyW593dypNwHqI55d97X4SMGcsvllz_Uhw

{
    "title" : "Otw Home",
    "date" : "Aug. 2, 2022",
    "content" : "Hi, I'm running everywhere!"
}