GET http://127.0.0.1:5050/profile
Cookie: random=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiZGF0YSI6eyJwYXNzd29yZCI6IiQyYiQxMCRmdmZTRUYzYnRyOUd3Qm5KTWw2bW8ubDdBN2xvcWg2aWRPWXZXRGNPZGhZMmZnazQxMUpjSyIsImxldmVsIjoyLCJzZWMiOjEyODAsImRhdGEiOnsibmFtZSI6Ikh1bnRlcnhIdW50ZXIiLCJhZ2UiOjIyLCJnZW5kZXIiOiJTbmFpbCJ9fSwiaWF0IjoxNjYwMDY2OTg2fQ.jjVVTdvfYtYgYzOUcALUQ5u06TROfDpuWBBYSR6FSsw